### ISSUE TITLE
Improve performance by serving static assets directly

### ISSUE THREAD

**Issue by chovanecm** [hotosm/tasking-manager#1429] opened 2019-03-30 20:49 UTC
Hi,

as mentioned in [my comment on one of the earlier commits](https://github.com/hotosm/tasking-manager/commit/2f11df096c4a7555fef6f95c7f4f7c4909158dc0#r32936950), it looks like Tasking manager performance could be (potentially significantly) improved if it didn't use Python to serve static assets like JavaScript files, SVG icons etc. instead of delegating the work to the web server.

Serving static content through Python means that the application has to read (potentially relatively large) files from the disk, buffer them and send them as a response through WSGI to the client. This takes time and blocks Python workers from serving other requests.
[The Flask documentation](http://flask.pocoo.org/docs/0.12/api/#flask.send_from_directory) for the `send_from_directory` function explicitly warns of this approach and recommends to handle static assets separately:

> It is strongly recommended to activate either X-Sendfile support in your webserver or (if no authentication happens) to tell the webserver to serve files for the given path on its own without calling into the web application for improved performance.

I believe it's worth giving it a try because the performance issues we experienced earlier this week at the time when several tens of people were using TM resembled overloaded python workers trying to serve every request (even those that could have been handled by the web server itself).
It would be nice if someone could have a look at it.

**Comment by qeef** [comment] 2019-04-02 06:05
The issue is tagged as *Needs help*. Can you write **what** you need help with?

**Comment by xamanu** [comment] 2019-04-02 07:39
It needs somebody who is taking a lead on implementing this.

**Comment by qeef** [comment] 2019-04-08 13:18
So I did a little bit of research and if I understand it correctly, it's more about server config then about development. It should be enough to update [.ebextensions](https://github.com/hotosm/tasking-manager/tree/11f0aa36b5fbc1911639e512fa3e8fc984fa27cd/.ebextensions) with [nginx config](https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/).

I guess that regular developers don't have access to AWS (i.e. for testing) so it depends on if someone from HOT developers would consider this issue significant?

**Comment by qeef** [comment] 2019-04-23 07:22
I don't want to spam but can this issue be solved by pull request? When you talking about "somebody who is taking a lead" it means somebody from HOT devs?

**Comment by xamanu** [comment] 2019-04-23 07:38
It is open for everybody to contribute! Please feel free to open a pull request with your solution.
We are happy to review any pull request coming in. Thank you.

**Comment by chovanecm** [comment] 2019-04-23 08:22
@qeef I think your idea to add an nginx configuration file (or to alter one of the existing) to [.ebextensions](https://github.com/hotosm/tasking-manager/tree/11f0aa36b5fbc1911639e512fa3e8fc984fa27cd/.ebextensions) might work.

Could someone tell me more about this file? ```/etc/nginx/sites-available/elasticbeanstalk-nginx-docker-proxy.conf```
It isn't versioned, is it? Because I see some in-place sed commands in ```.ebextensions``` to modify it.

Assuming there is no static content that should be protected from users that are not logged in, adding a few lines to that conf file should do the trick, e.g.
```
 location /assets/ {
     root /www/directory/assets; # example path
    # optinally, one can try also adding
   sendfile           on;
    sendfile_max_chunk 1m;
    }

```
https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/

**Comment by qeef** [comment] 2019-04-23 12:02
@xamanu I would like to contribute but still, I miss some information, and therefore I need guidance.

As @chovanecm wrote, there is no version control of `/etc/nginx/sites-available/elasticbeanstalk-nginx-docker-proxy.conf` file. From `.ebextensions` folder it looks like that the configuration is done by script changing the config file. This approaches looks strange to me, so why is that? How is the `/etc/nginx/sites-available/elasticbeanstalk-nginx-docker-proxy.conf` created?

Obviously, the tasks.hotosm.org application is hosted at Amazon AWS. From HTTP response headers and file name in scripts of `.ebextensions` I can guess that the tasks.hotosm.org is running nginx server (is it noted anywhere?). Because this issue targets server config, which file can be changed to solve this issue?

I understand that tasking-manager is a project used not just by tasks.hotosm.org. However, this issue solves *just* tasks.hotosm.org problem with nginx configuration. Is there different workflow for this kind of issue?

Sorry for a lot of questions but the answers will help me to understand the infrastructure and contribute to the project more effectively.

Thanks!

**Comment by xamanu** [comment] 2019-04-23 14:06
@qeef, we are currently moving away from Elastic Beanstalk to Cloudformation. @arunasank can give more information.

**Comment by arunasank** [comment] 2019-04-23 16:25
We have made some improvements to the performance using asynchronous workers on `gunicorn`, and moved away from nginx. 

The results of the load test are on https://github.com/hotosm/tasking-manager/issues/1354. We are able to handle about 3X the requests on production now. We want to move away from nginx - can we apply these fixes even without enabling nginx?

**Comment by qeef** [comment] 2019-04-24 07:29
Hi @arunasank, thanks for the information. I will check the [cloudformation](https://github.com/hotosm/tasking-manager/tree/cloudformation) branch more deeply.

> We have made some improvements to the performance using asynchronous workers on gunicorn, and moved away from nginx.

If I understand `gunicorn` well it's WSGI HTTP Server. I don't think that you can beat well configured `nginx + gunicorn` by just `gunicorn` in terms of performance. Even at the [deployment page of `gunicorn`](https://gunicorn.org/#deployment), there is the following note: *We strongly advise you to use nginx.*

> The results of the load test are on #1354. We are able to handle about 3X the requests on production now. We want to move away from nginx - can we apply these fixes even without enabling nginx?

No, as the discussion in this issue is about the static content not served by Nginx now. `gunicorn` serve the dynamic content, generated by python backend. The static content consists of javascript files, documents, or pictures. These are not needed to be served by `gunicorn` but simply by `nginx`.

I am going to explore the *cloudformation* branch in my spare time, maybe I will be able to find out the future architecture from that branch.

**Comment by arunasank** [comment] 2019-04-30 15:22
👋 @qeef 

Ok, I now understand your point with respect to static files. I was under the impression that `nginx` is only useful when one is working with proxying http requests or with caching, both of which we have eliminated with the new architecture. It makes sense to have all static content in the same directory, and serve those directly via gunicorn, and only route the pure backend requests to `gunicorn`. 

I am happy to walk you through our architecture if that would be helpful, and add this to my plate as something to look at.

**Comment by qeef** [comment] 2019-07-02 08:42
Hi again. As `cloudformation` was merged to `develop`, I checked the `develop` branch. I have to note that I can't help with AWS settings as I have never used it.

In https://github.com/hotosm/tasking-manager/blob/64cf03b3ad2ccb589305724732f4fc179698e7d0/devops/cloudformation/tasking-manager.template.js#L234 it looks like `gunicorn` is still serving everything, including static files.

I think there are currently two options:
1. Add nginx to EC2 and set it to properly serve static files.
2. Create new EC2 with static files only and redirect all the static traffic in ELB (ALB).

Or maybe I still don't understand your data flow design?

**Comment by willemarcel** [comment] 2020-05-22 19:07
It is already implemented in TM4.

**Closed by willemarcel** 2020-05-22 19:07 UTC
Labels: Component: Infrastructure, Difficulty: Medium, Status: Needs implementation, Type: Enhancement

**Comment by qeef** [comment] 2020-05-26 12:33
@willemarcel I can't find it in the repository. How have you solved it?

**Comment by willemarcel** [comment] 2020-05-26 13:45
@qeef on AWS, we build the frontend and serve it through a CDN instead of the gunicorn server. The views yet exist on the backend though.
