### ISSUE TITLE
Highlight status of project better

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#815] opened 2017-10-18 18:43 UTC
Look at http://tasks.hotosm.org/project/3647
This project was fully completed, validated and then archived, but you have difficutlies to locate this last info.
We just see the proeminent title and the priority (which has no use for archived projects)

We longer see "(archived)" or "(draft)" at top. and msot users will not notice it. You have to down the page to look for that, but they will first see the map of tiles : for some reasons some projects are cancelled and never completed, so they are archived. But users will start working on it.

Anyway the map is really too low on the page. Adn the status is a h text in the middle of the page.

Please put the status back at top (just beside where you put the priority in the small gray box above the title). In TM2 it was displayed as part of the title, just appended in parentheses and it was fine there and much better placed than where it is now.

**Comment by bgirardot** [comment] 2017-10-21 03:50
@verdy-p I am going to close this and make #814 the main issue, this seems like a duplicate of that issue.

**Comment by verdy-p** [comment] 2017-10-21 05:45
This is NOT the same issue: here I was speaking about what is displayed on an INDIVIDUAL project page difficult to see the status given the layout and the need to scroll that page and look into tiny properties). I was suggesting here to restore this status at top of the page (along with the project number, title, and priority)

in #815, this is raidically different I was speaking about WHICH projects are listed (the draft and archived projects are totaly invisible there).

**Comment by xamanu** [comment] 2019-04-10 19:22
This should be considered in the ongoing redesign with @hotosm/major.

**Comment by xamanu** [comment] 2020-03-19 11:15
This is still an issue with TM4. Lets move it to the roadmap for this improvement.

**Comment by willemarcel** [comment] 2020-05-29 11:52
We have labels for archived and draft now.

**Closed by willemarcel** 2020-05-29 11:52 UTC
Labels: Component: Frontend, Difficulty: Medium, Priority: Low, Status: Needs implementation, Type: Enhancement
