### ISSUE TITLE
Twitter Share Defaults

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#777] opened 2017-08-31 16:33 UTC
I think it would be better to include @hotosm by default versus #hotosm

**Comment by bgirardot** [comment] 2018-01-26 15:04
see issue #1035 for helpful information on how this issue could be resolved.

**Comment by xamanu** [comment] 2019-04-10 18:22
Let's mark this here as a duplicate of #1035

**Closed by xamanu** 2019-04-10 18:22 UTC
