### ISSUE TITLE
Problems posting to Questions and Comments on projects, failed posting some messages

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#857] opened 2017-10-22 17:33 UTC
Can't figure out why I can't post this message: 
![messageerror](https://user-images.githubusercontent.com/6763645/31864578-d4b9c7c4-b71c-11e7-8440-366a63e19000.PNG)

**Comment by bgirardot** [comment] 2017-10-22 17:36
I need more context, the whole page if you could screenshot the whole page.

this is on questions and answers page, i see.

and the project number would help to so I can see if I can reproduce

hope you are having fun russ!

**Comment by russdeffner** [comment] 2017-10-22 19:00
Yep, good times. Here's a screen shot of the whole page now, not sure that helps at all but it's 
http://tasks.hotosm.org/project/3665?tab=chat#bottom 
![messageerror2](https://user-images.githubusercontent.com/6763645/31865246-eac5ea32-b728-11e7-8336-9a10b1c66055.PNG)

**Comment by pgiraud** [comment] 2017-10-22 19:08
@russdeffner In case you think the issue is related to the text you want to post, please include it here.

**Comment by ethan-nelson** [comment] 2017-10-22 22:20
It appears spaces are not counted in the 'characters remaining' validation at the bottom of the box. Yet they obviously count as a character when stored in the database (and a message has a limit of 250 characters in the DB).

**Comment by alekno** [comment] 2017-10-23 10:35
https://stackoverflow.com/questions/26389745/how-to-count-the-number-of-characters-without-spaces
Mh, why should someone do this?
Maybe this is the old problem of not considering that a string count starts a position 0. So the last character is on position 249. Additionally the DB may count the \0 ( zero terminated string).
Just guessing.

**Comment by bgirardot** [comment] 2017-10-26 12:20
I am not able to reproduce this. I can create a message of 250 characters (0 characters left is displayed) and can post it fine.

**Comment by ethan-nelson** [comment] 2017-10-27 23:08
Okay it looks like the `characters remaining` _does_ count spaces, but it doesn't update the number until you add a non-space character. That is ruled out.

**Comment by ethan-nelson** [comment] 2017-10-27 23:33
Running locally it looks like links are formatted to include html in the raw message, which puts it over the limit. Attempting to find the code responsible for formatting.

**Comment by ethan-nelson** [comment] 2017-10-27 23:38
Code: https://github.com/hotosm/tasking-manager/blob/56d1d13056bbea342132cf6e78b12f01c73d5dd3/server/models/postgis/project_chat.py#L31

Documentation: https://bleach.readthedocs.io/en/latest/linkify.html

This will need to be tweaked: https://github.com/hotosm/tasking-manager/blob/164f58cbaf9d59f3c3e8c6c57fcb26e5791a6925/client/app/components/project-chat/project-chat.html#L29 

Double the characters included when adding a link + extra characters for `<a href="" rel="nofollow"></a>`? The issue is the javascript will need to parse in a similar manner, or at least be more aggressive when a possible link is added so the character limit isn't exceeded.

**Comment by verdy-p** [comment] 2017-10-29 15:55
Beware of the way you count characters: in Javascript we are measuring lengths in terms of number of UTF-16 code units (so a single Emoji from a supplementary space would count for 2 code units) but the data will be sent to the server encoded as UTF-8 (so a single Emoji from a supplementary space would count for 4 bytes). Then the webserver will store the string using the encoding declared for the database (could be UTF-8 or UTF-16) but the SQL backend may be setup to count either the Unicode characters, or the code units used to encode them and will have its own internal encoding (distinct from the encoding used between the SQL client in the webserver and the SQL server, and also distinct from the encoding used in the programming language used on the webserver for its own strings/buffers datatypes).
At each interface, there may exist some transcoding (and some transcodings may be eventually lossy if htey are not fully Unicode compatible, or may cause even the character length to be changed (for example if some Unicode normalization is applied, including during text transforms such as compression of whitespaces, or expansion/reduction of embedded links into some markup language)

**Comment by russdeffner** [comment] 2017-11-04 23:40
Now I can't post this:
@[ArneKimmig] oh, interesting - not sure there is a tag for those; you could search wiki.openstreetmap.org but I would leave them (no reason to delete the geometry) but maybe we need to come up with a tag.

**Comment by russdeffner** [comment] 2017-11-04 23:44
But this went fine: 
@[ArneKimmig] oh, interesting - not sure there is a tag for those; you could search the wiki but I would leave them (no reason to delete the geometry) but maybe we need to come up with a tag.

So, I'd have to guess it's something with URLs

**Comment by bgirardot** [comment] 2018-02-06 15:25
This is still an issue from my testing. It would be good to figure it out, but really 250 characters is much too short anyway, so a temporary solution might be to make that 500 characters, or even 750.

**Comment by ethan-nelson** [comment] 2018-09-23 17:17
It looks like this is fixed with #1174. Please reopen if you experience further issues after deployment to the live instance (for now you can test it at https://tasks-stage.hotosm.org).

**Closed by ethan-nelson** 2018-09-23 17:17 UTC
Labels: Guidance Included, Low Priority, bug
