### ISSUE TITLE
Improve Facebook share data

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#776] opened 2017-08-31 16:25 UTC
The Facebook share is only to the main Tasking Manager page.

please see issue #411 as to what we need to do to improve that.

**Comment by bgirardot** [comment] 2018-01-26 15:04
see issue #1035 for helpful information on how this issue could be resolved.

**Comment by xamanu** [comment] 2019-04-10 18:22
Let's mark this as a duplicate of #1035

**Closed** 2019-04-10 18:23 UTC
Labels: Type: Duplicate, Type: Enhancement
