### ISSUE TITLE
Can't update user email address on self-hosted tasking manager

### ISSUE THREAD

**Issue by DillonPinto** [hotosm/tasking-manager#1724] opened 2019-06-26 20:28 UTC
I get a Flask SMTP error "please run connect() first" (error code 500) when trying to update an email address on the tasking manager. Facebook, twitter and linkedin fields update if the email field is empty.

**Comment by xamanu** [comment] 2019-07-01 11:16
The quick fix would be to specify the following variables in `tasking-manager.env` configuration:
```
TM_SMTP_HOST=
TM_SMTP_PORT=
TM_SMTP_USER=
TM_SMTP_PASSWORD=
```

But we should present an error, but still allow the update of the email address.

**Comment by xamanu** [comment] 2019-07-08 12:33
This seems to be a duplicate of #1115.

**Closed by xamanu** 2019-07-08 12:33 UTC
Labels: Component: Frontend, Priority: Low, Status: Needs implementation, Type: Enhancement
