### ISSUE TITLE
Current Mappers Count

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#872] opened 2017-10-24 20:00 UTC
Please correct me if I'm wrong, but there is no more count of the number of mappers currently working a project displayed somewhere? As an enhancement, it would be great to have also the total number of mappers on the whole TM somewhere.

**Comment by pgiraud** [comment] 2017-10-24 20:12
I miss that feature a lot too. It was a good way to be aware of activity.

**Comment by bgirardot** [comment] 2017-10-24 21:11
This should probably be a high priority issue. With the regression label.

**Comment by Boggedy** [comment] 2017-10-24 23:17
should be high priority....it acts as a magnet and the overall tempo will drop without it.

**Comment by pgiraud** [comment] 2017-10-25 09:09
Duplicate of #627.

**Closed** 2017-10-25 09:14 UTC
Labels: High Priority, regression
