### ISSUE TITLE
Changeset comment not auto-filled

### ISSUE THREAD

**Issue by jflasher** [hotosm/tasking-manager#2893] opened 2020-05-07 16:25 UTC
On the new tasking manager (looks great by the way!) it looks like the changeset comment isn't auto-filled when getting ready to save like it was previously. I see the comment at the bottom of the Instructions tab on the right sidebar and am just copying over manually.

**Comment by xamanu** [comment] 2020-05-08 13:44
Thank you. This is a duplicate of this issue: https://github.com/hotosm/tasking-manager/issues/2650
Closing here.

**Closed by xamanu** 2020-05-08 13:44 UTC
Labels: Component: Frontend, Priority: Critical, Status: Needs implementation, Type: Bug
