### ISSUE TITLE
Revisit prominence of bad imagery button

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1329] opened 2019-01-18 16:42 UTC
Per TWG meeting and https://github.com/hotosm/tasking-manager/pull/1319#issuecomment-453905106

The button rearrangement has caused an increase in tasks marked bad imagery. This could be due to the prominence of the bad imagery button, but may also stem from low bandwidth or inattention to custom imagery.

We should consider moving/shrinking the button so that the unlock button is more visible.

We could also consider limiting the bad imagery button to only users of medium and advanced mapping levels.

**Comment by Vaomatua** [comment] 2019-01-22 02:09
Thanks Ethan, restricting the bad imagery to a mapper level is a good idea.
Personally I mark a tile as validated when I verify that all 5 valid imagery sources are not useable. That way other validators don't continue to revisit the tile and we can get to 100% validation to archive the task.

**Comment by russdeffner** [comment] 2019-01-24 00:35
I would respectfully disagree; the main reason we added a bad imagery button was because we had many mappers marking tasks as done because they didn't have good imagery, or impatient with it loading, etc. I think we want new mappers telling us that there isn't sufficient imagery (when there really isn't); I think the problem is still more about them being confused on how/when to unlock vs. marking complete (or something else such as bad imagery). Taking it away will just go back to more tasks being marked done, when they are not.

**Comment by Vaomatua** [comment] 2019-01-25 18:51
@ramyaragupathy  Great analysis, thanks. 
I noticed the problem quite a bit on task 5588, I suspect the percentage of tasks tagged as bad imagery is higher than  0.045%. I believe all of the ones I looked at were created using the iD editor. On the Crowd2map Slack channel I have had to explain dozens of times how to switch the background images. For new editors that don't read or ask questions having a big "bad imagery" button is an easy choice if Bing is fuzzy.
For example yesterday https://tasks.hotosm.org/project/5588?task=3364 was tagged as bad imagery, all 5 image sources (Bing, DG-2, Esri-2) are fine.
@russdeffner  Russ, what do you disagree with? I think we still need the Bad imagery button, just not with the size and prominence as @ethan-nelson suggests.

**Comment by russdeffner** [comment] 2019-01-25 18:53
@Vaomatua - just the hiding it from Beginners (i.e. restricting the button to intermediate and advanced). Agree that it's prominence is maybe too high with current interface.

**Comment by Vaomatua** [comment] 2019-01-25 19:12
@russdeffner Thanks. I think another consideration is the impact of a "false positive", (a tile with good imagery marked as bad imagery) which is then marked as "invalid". That notice can be a real discouragement to any mapper, especially new ones.

**Comment by xamanu** [comment] 2019-05-09 17:26
@Vaomatua Do you think this can be resolved with the envisioned and [proposed redesign](https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/358973362)?

**Comment by Vaomatua** [comment] 2019-05-09 21:20
@xamanu Thanks for sharing the redesign. I like it, I think that if the "Satellite imagery is not good" box were checked the user should also have to specify which image service is causing the problems. My observation is that newbie mappers see clouds on Bing, and then say the Satellite image is bad. There needs to be some way to communicate that there are other imagery options available.

I'm not sure of the the purpose of "This task is already mapped".

Edit Status Suggestions:
[  ] Satellite imagery is not good, (Specify image source ________________ )
[  ] This task is completely mapped
[  ] More mapping is needed

**Comment by xamanu** [comment] 2020-04-13 09:13
We went over the naming of states for TM4. Considering this as closed.

**Closed by xamanu** 2020-04-13 09:13 UTC
Labels: Component: Frontend, Type: Enhancement
