### ISSUE TITLE
[BUG] Contact us form on website doesn't work

### ISSUE THREAD

**Issue by CodefortheCarolinas** [hotosm/tasking-manager#5569] opened 2023-02-07 15:29 UTC
**Describe the bug**
The [Contact Us form on the Tasking Manager website](https://tasks.opensidewalks.com/contact) doesn't work.

**To Reproduce**
1. Go to '[Contact Us form](https://tasks.opensidewalks.com/contact)'
2. Click on 'Contact Us button.'
3. Fill in all three fields
4. Click Send
5. See error

**Expected behavior**

I expected the message to send and to get a confirmation of that message. Or at least for the box to close with no error message.

**Screenshots**
<img width="545" alt="image" src="https://user-images.githubusercontent.com/99441930/217284652-2a9a14e5-6a02-4a16-bf40-578d9eef21da.png">

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser [Chrome]
 - Version [Version 109.0.5414.120 (Official Build) (64-bit)]

**Additional context**
I am trying to get in touch to start a new project.

If I click Send again, nothing happens. No error message, but the form also doesn't clear or seem to submit. If I refresh and fill in the form again, I get the error message again.

The error also happens when using Firefox. It also happens whether or not I am logged in.

**Comment by Aadesh-Baral** [comment] 2023-02-08 07:53
Hi @CodefortheCarolinas  This seems to be the issue with the particular instance of Tasking Manger  i.e. OpenSideWalks Tasking Manager. 
There might be missing configuration `TM_CONTACT_EMAIL`  by the development team during the deployment. For this, You can create a issue in [OpenSidewalks/tasking-manager](https://github.com/OpenSidewalks/tasking-manager). 

Closing this as the problem is with configuration setup rather than the code itself.

**Closed by Aadesh-Baral** 2023-02-08 07:53 UTC
Labels: Type: Bug, Backlog=triage
