### ISSUE TITLE
multiple task validation layers

### ISSUE THREAD

**Issue by govvin** [hotosm/tasking-manager#1026] opened 2018-01-17 02:41 UTC
Shouldn't the content of "Data Layer 2" be in the "Task boundaries" layer?

When I choose to select validation by user, I get these layers in JOSM

- **OSM data**, I assume is the layer you want to work on, where you download data from OSM
- **Data Layer 2** contains the task boundaries, in one layer
- **Task boundaries XXX - Do not edit or upload** - is an empty layer

![image](https://user-images.githubusercontent.com/5821688/35022778-abfd5694-fb72-11e7-8826-4e9d57e08a85.png)

I found it more useful to convert the layer boundary to GPX, because the color can be changed, and is visible while working on the data layer.

**Comment by bgirardot** [comment] 2018-01-25 02:31
Did all of those layers get created or did data layer 2 already exist before you lauched the editor from the tasking manager?

**Comment by govvin** [comment] 2018-01-25 02:33
All those layers we're created. Except for imagery, i had no data layers opened in JOSM.

**Comment by xamanu** [comment] 2019-05-23 10:28
This seems to be a duplicate of #637.

**Closed by xamanu** 2019-05-23 10:28 UTC
Labels: Type: Duplicate
