### ISSUE TITLE
Projects being loaded takes much time

### ISSUE THREAD

**Issue by richa031** [hotosm/tasking-manager#1408] opened 2019-03-25 17:37 UTC
It takes very long time to load the projects on the website. As a user people think there are no projects and move to other links.

![Screenshot from 2019-03-26 00-22-24](https://user-images.githubusercontent.com/32764563/54941335-9b202b00-4f52-11e9-9e19-14d02359cc98.png)

We can check if something can be done here.

**Comment by ethan-nelson** [comment] 2019-03-26 02:57
Hi @richa031 thanks for your interest in this! It's definitely a problem. This issue is a duplicate of #1188, so I'm going to go ahead and close this so we can consolidate all the information there. If you are interested in tackling this problem, I have some advice on that ticket actually towards solving this problem. Cheers!

**Closed by ethan-nelson** 2019-03-26 02:57 UTC
