### ISSUE TITLE
Overpass View Broken

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1529] opened 2019-04-28 00:33 UTC
When I try (as Admin) to view a mapper's work on a project (by viewing their Project history on their Profile page), the overpass turbo view link does not work.
![Overpass](https://user-images.githubusercontent.com/6763645/56856572-e1cebf80-691a-11e9-8463-3f0f563a0fbf.PNG)
This is what it looks like with Firefox dev console open.

**Comment by JorgeMartinezG** [comment] 2019-04-30 17:18
to make an update in this issue, commit https://github.com/hotosm/tasking-manager/commit/3fc4b711fb40d1a2b5a9502ffb1ab7897966d566 removed the project geometry in the returned data when client requests mapped projects from an user. This causes an undefined variable in javascript:

https://github.com/hotosm/tasking-manager/blob/develop/client/app/profile/profile.html#L313

Including the project geometry as geojson within the response would solve the issue, but I would like to know your opinion @ethan-nelson before creating a PR.

**Comment by ethan-nelson** [comment] 2019-05-05 16:25
I guess the issue here is that we removed the geometry since it was fairly expensive computationally...it would take up to a minute to load some people's activity or flat out fail with an HTTP error if it took even longer (see #1144 for more background).

I wonder if there's a way we could load the geometry for overpass just-in-time or perhaps take advantage of something like GPX of the AOI from another API endpoint (e.g. pass a url of project GPX to overpass to use in the query). Other ideas welcomed as well.

**Comment by JorgeMartinezG** [comment] 2019-05-07 13:11
@ethan-nelson server has an endpoint to get project aoi `/api/v1/project/<int:project_id>/aoi`, but this service is not being included in the client. We can include a service in _project.service.js_ file which executes a request to this endpoint and get the aoi. This will be done each time the overpassturbo of a project is run, using the id rendered. My opinion is that it will solve the issue without sacrificing performance.

What do you think?

**Comment by ethan-nelson** [comment] 2019-05-08 01:59
Sounds like a good strategy :+1:

**Comment by michael63-osm** [comment] 2019-06-23 11:15
@ethan-nelson , @xamanu 
Looks like I have no permission to reopen this bug but since a few days the overpass view is broken again. The links only point to the start page of TM

**Comment by ethan-nelson** [comment] 2019-06-23 16:56
@michael63-osm could you provide a little information of what you tried and on what page? Did you click on the button on the user project overview? Do you have any strict popup or ad blockers?

We use a javascript function now for the button to generate the link just in time. When the "view in overpass" link is clicked, the javascript then pings the database for the project information, generates the correct overpass link, and opens a new tab with that link. This is because otherwise the database can get overwhelmed when you load someone's profile as it has to look up full project information for every project someone has contributed to when all those links aren't necessarily needed immediately.

**Comment by michael63-osm** [comment] 2019-06-23 18:15
Sorry for the confusion - javascript was for some reason blocked when I tried this. I can confirm that without this it works. I guess it would be clearer if the link did not read like the TM start page but rather javascript() or something similar as I saw on other websites.

**Comment by xamanu** [comment] 2019-06-24 08:43
Thanks @michael63-osm and @ethan-nelson. Closing here again.

**Closed by xamanu** 2019-06-24 08:43 UTC
Labels: Difficulty: Medium, Priority: High, Status: In Progress, Type: Bug
