### ISSUE TITLE
Incomplete (not done) Timeout issue

### ISSUE THREAD

**Issue by Boggedy** [hotosm/tasking-manager#828] opened 2017-10-19 10:59 UTC
In the old UI a noob would often take a tile and do nothing with it. After 2 hours the taken tile would time out releasing the task back to another mapper. 

I see tasks taken for 6 hours ..and not marked done and not released back.... in the new UI. 

EG > http://tasks.hotosm.org/project/3665?task=48#bottom

**Comment by verdy-p** [comment] 2017-10-23 20:29
invalid: it just indicates this talsk was locked for 5 minutes. The status shows a yellow tile, so it is no longer locked. The task editing buttons are working properly on this mapped tile (you can still validate it or invalidate the initial mapping).

May be you are confused by the fact you can't "start validating" the tile if you've not selected the correct tab at top: this is a confusive interface and both tabs should be merged as a single one, with the correct edit/validate/invalidate/split buttons according to the current state of the selected tile (it was fine in TM2)

So yes the UI should be refined and this may qualify as a regression (but not severely blocking)

**Comment by bgirardot** [comment] 2017-10-26 12:33
@Boggedy This is also really hard to test. I know we are making sure this works as intended.

It is a known issue that there is no UI to display the time left.

But I know I did test the 2 hour time limit and it was getting released properly. I have not tested it recently, but I will (takes at least 2 hours :)

**Comment by bgirardot** [comment] 2017-12-20 05:57
These are getting released properly after 2 hours. However there is no entry put in the task history to reflect it was ever checked out and then unchecked out, kind of a separate issue.

Please let me know if I am missing something @Boggedy and please just re-open this if I am.

**Closed by bgirardot** 2017-12-20 05:57 UTC
Labels: invalid, UI Refinement
