### ISSUE TITLE
Duplicate entries for priority_areas

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1789] opened 2019-07-25 12:57 UTC
From chat, it was flagged today that the project save threw a weird error for specific projects.
![image](https://user-images.githubusercontent.com/12103383/61873336-5b1e8400-af03-11e9-8ef3-2d7e1f20044c.png)

From further investigation, 
- There are duplicate entries in project priority areas. A total of [808 priority areas across 469 projects](https://docs.google.com/spreadsheets/d/1aYVNWLEZJDMAceyoEl-IaWMMdWeRpQ2VO5HKpxC4EzE/edit#gid=0) have exactly 6 entries for each priority area marked within the project.
- During project update(each time the save button is hit), I notice the old entries related to projects are removed from the priority areas table and new rows are created with different priority area ID

For the 469 projects which have duplicate priority area ID, save function fails in the second step, where old entries are removed and new entries are created.

Going further:
- we should remove the duplicate entries
- make sure the most recent priority area is retained

However I could not narrow down the reason for the duplicate entires

**Comment by xamanu** [comment] 2019-07-25 13:38
@ramyaragupathy, are the duplicated entries only caused by old projects (coming from before the migration from TM2 to TM3)? Or also on most recent ones?

**Comment by ramyaragupathy** [comment] 2019-07-26 06:39
I see this issue for about 100+ projects from TM3 as well. So it applicable across versions of TM @xamanu

**Comment by ramyaragupathy** [comment] 2019-09-25 10:31
This also leads to project archive failure. Example:
https://tasks.hotosm.org/project/4908
https://tasks.hotosm.org/project/4772

**Comment by mapconcierge** [comment] 2019-09-25 18:45
Thanks! @ramyaragupathy

**Comment by xamanu** [comment] 2019-10-02 13:54
This has been merged into the `develop` code base and was added to our deployment plan for version 4. Then it will be live.

**Closed** 2019-11-07 15:31 UTC
Labels: Component: Backend, Difficulty: Medium, Priority: High, Status: Done, Type: Bug
