### ISSUE TITLE
Messages - Inbox Filter for Task should use editbox instead of spinner control

### ISSUE THREAD

**Issue by wireguy** [hotosm/tasking-manager#1655] opened 2019-05-30 12:57 UTC
Task values are numbers, so a spinner control was selected.

But if a user wants to go to a specific task, say 583, they are not going to press the up arrow on the spinner 500+ times.   

Also, the spinner allows for negative values (-34) and also exponential values to be entered (1e42, 1e-42, 1e+42 or even just 'e').  Tasks numbers will never be negative or exponential.  The result filters out all entries in the inbox.   

A better user experience would be to use an editbox control, and allow for partial match on the filter.    For example,   if I only remember the task had the number 42 in it, allow me to  type 42 in the editbox and filter the result showing tasks that contain 42 anywhere in the number (example  42, 542, 420, 13423).

**Comment by xamanu** [comment] 2019-10-02 16:11
Thanks for the input! This is related to the new notifications page #1644

**Comment by xamanu** [comment] 2020-04-13 09:20
This functionality has been descoped in the design for TM4. Therefore not a bug anymore. Closing here.

**Closed by xamanu** 2020-04-13 09:20 UTC
Labels: Component: Frontend
