### ISSUE TITLE
Add functionality to split tasks for validation

### ISSUE THREAD

**Issue by dbdean** [hotosm/tasking-manager#937] opened 2017-11-08 00:36 UTC
Sometimes when validating, it's useful to be able to split the tile before validating.

Example scenarios:

1) It is a very complicated tile, and you'd like to make it simpler to validate.

2) Some parts of the tile have bad imagery, and you'd like to split the tile to indicate which parts have bad imagery. This is related to https://github.com/hotosm/tasking-manager/issues/936, which I posted separately.

**Comment by verdy-p** [comment] 2017-11-29 20:12
For now you need to first invalidate the tile in the "validation" tab, tu turn it to violet/magenta, then go to the "map" tab and "start mapping" it (the tile turns to blue and is locked), and then "split" (this creates 4 new subtiles which are back to white.

Unfortunately, since TM3, you cannot do that on a project which has "draft" or "archived status" (it must first be "published", even if at the lowest priority), and when you do that, TM3 no longer displays the history of events (locked-for-edit, unlocked, done, mapped, validated, invalidated, splitted) that occured in the previous larger tile (this history was kept in TM2, but apparently it was duplicated in all subtasks and this duplication of history is no longer occuring in TM3, and also not visibly linked to the previous larger task number).

So yes this is a regression bug since TM2.

**Comment by hunt3ri** [comment] 2017-11-29 21:49
My view was that keeping the history didn't make sense.  Comment/discussion about the full tile would no longer apply to the split tiles.  eg you are talking about a feature/issue in the top right corner of the full tile that wouldn't exist  in the 3 of the tiles once split would seems v. confusing to me??

**Comment by pgiraud** [comment] 2017-11-29 22:00
@hunt3ri I fully understand your point of view. I tend to agree. However as far as I remember keeping the history for a split task was asked by users and thus implemented. It should be easy to find issues or pull requests where it has been discussed.
I can't decide whether or not we need to keep this feature. Previous discussion threads may help.
By the way, keeping the history of split task was not the initial subject of the current issue. It should probably be discussed elsewhere.

**Comment by verdy-p** [comment] 2017-11-29 22:37
comments about the full tile will still make sense after the tile split (which will also be visible in the history). The case scaneario is that we have various mappers doing the initial mapping very fast with poor quality, but at validation step we see that there are already too many details and various things to fix that are spread on places difficult to see: splitting is needed to help the effetive review, and many parts will be easier and faster to validate than the big tile. The history also shows who mapped the tile, and we cannot then talk to them to inform about why this mapping was not so good and that they should have splitted the task before marking it done.
So let's see what happens: duiring validation we need to invalidate (even if there's not many things to really invalidate) then return to mapping only to split the tile but most of the mapping is still done and only validation is needed to fix the small issues (note that we may need to split some subtile again)
In all cases: the history of a split tile should include a link to the previous task before the split, and the history of that former task should then be displayed just below it (assuming we are showing the history from the most recent event first at the top), possibly after clicking a link to retrieve the history of the former task (so the actual display does not need to perform multiple recursions, it will be done by a user action on a "show more..." button).

But yes we do need to be able to split for validating any tile that has been marked as "done", notably because mappers (not validators) frequently forget to zoom in to see all details, and don't use the split themselves (even if we instruct them to do it): they don't believe that what they did was so bad or imprecise or that they have left various unexpected interection issues (notably within dense city areas like Mexico City, or San Juan in Puerto Rico, or many dense but poor cities that we manage in HOT, such as African cities or in the Middle East)

**Comment by verdy-p** [comment] 2017-11-29 22:41
Note that when we split a task, the previous task is not really deleted, it just becomes inaccessible on the map (but if you look at the "exported" JSON, they are still there, including their geometry: the splitted tasks are just squares on top of the previous unsplitted task). And it's interesting to keep a link from the new subtasks to the previous larger one: so please add it in the record, and the first event recorded in each of the new subtasks will be the link to the previous task (which should still be in the database)

**Comment by xamanu** [comment] 2020-03-05 12:07
To me it seems not an important feature, but introducing quite a lot of complexity. I would abstain from implementing this right now.

**Closed** 2020-03-05 12:07 UTC
Labels: Priority: Low, Type: Enhancement
