### ISSUE TITLE
Logo for new partnership page should be able to be uploaded directly

### ISSUE THREAD

**Issue by nicolelaine** [hotosm/tasking-manager#6619] opened 2024-11-06 12:25 UTC
**Is your feature request related to a problem? Please describe.**
As it stands, we are moving away from the Missing Maps website for our corporate partnership pages. Right now, when one wants to upload the partner logo to the new partnership page, you still need to grab the link from the Missing Maps Github, instead of being able to upload it directly. 

**Describe the solution you'd like**
A user can upload the logo directly to the new partnership page, and no longer needs to rely on the Missing Maps Github to host the logos.

**Comment by ramyaragupathy** [comment] 2024-11-13 08:24
duplicate of https://github.com/hotosm/tasking-manager/issues/6563

**Closed** 2024-11-13 08:30 UTC
