### ISSUE TITLE
Forbid Project Managers to assign same role to other users

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#1442] opened 2019-04-07 02:59 UTC
Urgent, Urgent Regression from TM2!!!

Project Managers should not be able to give others the PM role. We desperately need to control who gets PM role and ensure they are properly trained. Just found out that PMs currently have the ability to give others the role and this dramatically limits our ability to control this, and is a regression from how only Admins could give the role in TM2. Only Admins should be able to give the PM role!

Can we please expedite this change so the problem does not get worse; thank you!

**Comment by xamanu** [comment] 2019-04-08 09:39
Thanks for the PR, @ethan-nelson. It fixes the urgent part of the issue, because project managers can't give the role to other users (lowering the priority here).

![image](https://user-images.githubusercontent.com/97706/55714467-406ee080-59e2-11e9-915c-eab85b44afa6.png)

In order to consider this issue to be fixed, ideally the button to promote to a "Project Manager" should be hidden, similarly to the "Adminstrator" button.

**Comment by xamanu** [comment] 2019-04-08 10:12
Hiding the button should be [strait forward](https://github.com/hotosm/tasking-manager/wiki/Restricting-features-to-certain-users).

**Comment by uwaiszaki** [comment] 2019-04-08 11:55
@xamanu can I work on this?

**Comment by xamanu** [comment] 2019-04-08 16:40
Of course. Your valuable contribution is always welcome!

**Comment by ethan-nelson** [comment] 2019-04-09 00:23
Do you recall what your rank was when you tested this? The project manager button [should](https://github.com/hotosm/tasking-manager/pull/1443/files#diff-be8300f768292433fee89008fc65dc70R218) only show up for TM admins.

**Comment by xamanu** [comment] 2019-05-07 11:54
I can confirm it works! Thanks. Closing here.

**Closed by xamanu** 2019-05-07 11:54 UTC
Labels: Difficulty: Easy, Priority: Low, Status: In Progress, Type: Bug
