### ISSUE TITLE
enable export grid option for all, and add user id info on it

### ISSUE THREAD

**Issue by ViolaineDo** [hotosm/tasking-manager#592] opened 2017-06-21 06:45 UTC
It would be so helpful to :
- Enable any user to download the grid of the project, which is currently only possible by the project  managers.
- add the user id that completed the task, or validated it on the exported grid, so that it would give more flexibility on the validation process...

**Comment by bgirardot** [comment] 2017-10-24 15:00
@ethan-nelson @pgiraud This is the issue violane has as urgent and I agree, it is urgent.

**Comment by verdy-p** [comment] 2017-10-24 18:02
I agree it is missing, but you can still get the data using your browser:
- Go to the project page where the map is displayed, open the browser's developer panel, go to its "network" section.
- Refresh the page, and look at the list of "XHR": you'll see one request whose result in the content body is the JSON file used to render all tiles on the map. You can copy-paste this JSON to a text editor and save.
- You don't need to be a project manager to get this data (and it works also on TM2, or other TM instances where you're not a project admin). Basically this XHR is part of the documented TM server API.

**Comment by pgiraud** [comment] 2017-10-24 19:53
I may be wrong but the the request @verdy-p talks about has a simple URL which should look like:
http://tasks.hotosm.org/api/v1/project/xxx

**Comment by hunt3ri** [comment] 2017-10-24 20:53
@pgiraud is correct.  We built the restful API to make it easy for developers to extract TM info without having to scrape the page.  It's documented here

http://tasks.hotosm.org/api-docs

**Comment by ViolaineCartONG** [comment] 2017-10-26 09:53
Hi @hunt3ri Actually, I couldnt find the tool in the API (I'm not a developper). I tried _GET /api/v1/project/{project_id}/tasks-as-osm-xml_ but the issue is it looked like I needed to specify specific tasks I want to extract. I want all so I tried with "*", it returned "500" error . Nevertheless  with the adress @pgiraud suggested, I could extract the info only related to the grid. It's far from straight forward for our retired volunteers ^^ Is there a thing that could make it easier, a thing that I missed? Thanks

**Comment by verdy-p** [comment] 2017-10-26 11:20
For project 3648 (just an example) the following address is correct:

http://tasks.hotosm.org/api/v1/project/3648

It is effectively this URL which is used by the rendered map in the project page to retrieve the GeoJSON.

The suggestion by @pgiraud is equivalent to the one I made by looking for XHR requests in the network panel of the developers tools built in modern browsers, the address is exactly the same.

How can it be simpler?

**Comment by bgirardot** [comment] 2017-10-26 11:31
@verdy-p It could be simpler if when you clicked on the url it went to a save file dialog box, with a good default file name, instead of displaying a mess of xml.

Is it hard to make it do that or add another api end point that would?

**Comment by bgirardot** [comment] 2017-10-26 11:32
@ethan-nelson Also I believe Ethan, who is unavailable this week has also looked at this issue in the past and might have made preparations to support it like old skool TM2 with a link on the project page.

**Comment by bgirardot** [comment] 2017-10-26 11:40
Also, the resulting file, when using "save as" comes with no extension and even after adding the extension it does not open in JOSM, JOSM returns an error.

**Comment by verdy-p** [comment] 2017-10-26 11:55
That URL can be used with "save as" with a right click, ot you can use the "File>Save as" in your browser. It just appears that browsers do not propose automatically a "save as" dislog when the content type is plain-text as it can be rendered as is. This is not part of any API, it is the standard behabior of web browsers for Content-Types on the web when all you have is an URL (if you just click an HTTP or HTTPS URL without any HTML code to specify an alternate behavior, the browser will just perform a GET on it, will retreive the result status and if successfull, will look at the media type in the reply to know how to render it (it opens a dialog only for content types that are not renderable such as executable files, but will not open any dialog when you point to a text document, if it was an HTML content type, it will use an HTML parser).

Note: there's **no** XML here, this is pure GeoJSON.

It's notmal there no extension because the URL specifies none. Extensions in URL are never warrantied to be present (e.g. "http://wwww.example.com/" also has no extensio, though it is still returning HTML and instead of the extension, there's a "Content-Type". If you use save as, it's up to the browser to propose a default file name (with extension if needed for your local OS, but MacOS or Unix/Linux do not need extensions but use other ways to identify content types. Extensions are used in DOS/Windows/VMS or older systems that need them as part of the filename, but they are also no longer required on Windows and content-types specifying a behavior of the file on your OS such as determining the application to open to read it are not dependant of these old "extensions".

The only way to propose a default filename, is not by a simple URL, but by embedding the URL within some custom HTML element that will enforce the "Save as" dialog and a default filename along with the source URL and possibly within an alternate or new separate tab/window. This is exactly the same for PNG/GIF/JPEG images on the web where you find an URL!

If you don't like the fact that the browser will by default render it as a plain-text file, you may setup your own content-type assocations in the browser.

I have no problem with opening these GeoJSON files in JOSM (provided you've installed the suitable plugin for GIS tools that adds support for importing/exporting files).

**Comment by bgirardot** [comment] 2017-10-26 12:00
@verdy-p Thank you very much, that was quite helpful. For some reason I always think GeoJSON is XML.

Anyway, I still  can not open your example url resulting file, after adding the .json extension.

GeoJSONLint also returns an error on the contents of that file:

![2017-10-26_13h58_06](https://user-images.githubusercontent.com/265831/32051688-f331acf8-ba55-11e7-816e-35852e9510fb.png)

**Comment by verdy-p** [comment] 2017-10-26 13:08
This is not a bug of the GeoJSON file, but currently the Tasking Manager will not accept a GeoJSON whose internal type is a "FeatureCollection" or "Feature", it only accepts a single geometry with "type":"Polygon" or "MultiPolygon" for creating an AOI (the same is true for the Export Tool).

The exported tilesets from TM however is a feature collection. You need manual editing with an external editor to transform the GeoJSON within a single
 {"type": "Polygon","geometry": [ [outer ring1], [inner ring], ...]}
or
 {"type": "MultiPolygon","geometry":[ [[outer ring1], [inner ring], ...]], [[outer ring2], [inner ring], ...]], }

Also, when saving an OSM file in GeoJSON format, it actually saves using a "Linestring" type of geometry representing lines, but not their enclosed surface.

For the export tool, the "Feature" types are not accepted.

This type of transform is easy to do with a simple text editor. But it is still needed.

**Comment by verdy-p** [comment] 2017-10-26 13:20
Note that the export from the URL above does not contain only the GeoJSON data: it is part of a larger JSON dataset, which also include non-GeoJSON properties. The only relevant subset to use is in the "{value in braces}" given to the "areaOfInterest": property,
or the list of tasks given as a FeatureCollection.

**Comment by verdy-p** [comment] 2017-10-26 13:22
It may be tricky for you, but there exists some JSON data editors that allow parsing and editing it in a treeview with a more friendly presentation.

**Comment by ViolaineCartONG** [comment] 2017-10-26 15:14
@verdy-p issue i was pointing is exactly that : you need to edit the json info (from @pgiraud adress) which is not straight forward. It's doable but not for everyone.

**Comment by verdy-p** [comment] 2017-10-26 19:05
Editing was ALSO needed with the file loaded from the "Export" link in TM2 (which only provided the GeoJSON of tasks, but the not GeoJSON of the AOI or other properties of the project (which are not in GeoJSON).

So in all case this was not so trivial in all cases because there are different uses of the data (more or less filtered) and the GEOJSON for the "tasks" was and remains a "FeatureCollection" (still valid but not valid for importing an AOI into the TM for a new project, and not very suitable as well for importing the covered area in the Export tool where the arbiotrary division of tiles causes some connectivity defects or some missing features in the export)

The basic need is still to export the geometry used in TM as is, but it will not prevent reworking that geometry, filtering unneded properties from each feature container as well as the container and its own properties).

The URL from the API contains everything needed, but it's not very complicate to edit it in a plan text editor, and do some gerometric transforms in JOSM (then reedit it to make the [Multi]LineString created by JOSM when saving, back to [Multi]Polygon geometries that other tools will want.

You may still use a visual JSON editor, but the JSON format is very simple to parse even manually or with basic search&replaces (in plain-text or with simple regexps)

There's various possible use of the generated JSON for different applications, and adding more filters would complicate the interface, The basic API URL above is all that is needed to cover all uses (filtering can still be done externally, these JSON are not very complicate)

**Comment by bgirardot** [comment] 2017-10-26 19:25
@verdy-p Certainly appreciate all the info. However, you do not know all use cases, nor everyone's skills, so blanket statements like "The basic API URL above is all that is needed to cover all uses" is not accurate because it fails to take into consideration the user's skills and needs.

I am not editing JSON to open it in JOSM, which i never had to do with TM2 output. We should be able to manage that, which is probably the most common thing folks like to do.

Also, the TM2 would output the original AoI, just via a different url than the one that output the tasks. But most people used the tasks json because that covered what was actually mapped vs. the original AoI.

**Comment by verdy-p** [comment] 2017-10-27 11:26
when I wrote "cover all uses" it means all use of infos it contains. As different aplications have different needs, what would need to be filtered for specific ones would require creating as many  output options as third party apps.
However it's true that the full JSON from the XHR API is a specific JSON format for TM and not pure GeoJSON. The full JSON embedd at least two GeoJSON, one for the tileset, the other for the AOI.

**Comment by JorgeMartinezG** [comment] 2019-04-25 20:54
@xamanu the geojson export has been included in #939.

**Comment by xamanu** [comment] 2019-04-26 07:57
Thanks, @JorgeMartinezG. Closing here

**Closed by xamanu** 2019-04-26 07:57 UTC
Labels: Status: Needs implementation, Type: Enhancement, Type: Regression
