### ISSUE TITLE
It doesn't seem possible to sort the projects by newest first.

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#988] opened 2017-12-10 14:33 UTC
You only appear to be able to look through them in priority order.

If you're looking fora new project to sit and validate on this is on problem.

**Comment by rhcu** [comment] 2018-03-09 10:41
Hi! I want to start working on this issue. Can you elaborate on it?

**Comment by johnwhelan** [comment] 2018-03-09 13:20
I know very little on the programming side.  If you can spot were it sorts them into priority order then it should be possible to add an option for sorting into time order.  ie the most recent project first.  It was available nder the old TM 2.

Thanks John

**Comment by bgirardot** [comment] 2018-03-13 16:08
Hi @rhcu I am not sure where in the code this sorting is done either. I would guess it is in the client directory somewhere and handled by the AngularJS code. As John says, I would grep around for where it sorts by priority and see if you can sort by project number instead which is kind of a proxy for "newest".

It would also add a UI item to control the sorting.

I can not promise this is "Easy" and will remove that label. It might be easy, I just do not know and am not sure verdy knows for sure either :)

Perhaps @LindaAlblas could point you to the spot in the code to start reviewing this.

**Comment by bgirardot** [comment] 2018-08-03 13:06
This is a duplicate of #803 so I am closing this one. Thank you for the issue @johnwhelan we need more sorting options for sure.

**Closed by bgirardot** 2018-08-03 13:06 UTC
Labels: Medium Priority, UI Refinement, regression
