### ISSUE TITLE
User warning for large project extent

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1915] opened 2019-10-10 16:48 UTC
Our average project size stands at 5500 sq.km, but there are 400+ projects exceeding the average extent. Per chat w/ @willemarcel @dakotabenjamin and @eternaltyro a user warning
should be provided during project creation

**Comment by xamanu** [comment] 2019-10-10 17:48
Yes, good step. Is this a duplicate of https://github.com/hotosm/tasking-manager/issues/1080?

**Comment by xamanu** [comment] 2019-11-05 08:11
@JorgeMartinezG Can this be included in the TM4 project creation (https://github.com/hotosm/tasking-manager/issues/1888) you are currently working on?

**Comment by xamanu** [comment] 2019-12-12 12:58
This has been included. Closing the issue here.

**Closed by xamanu** 2019-12-12 12:58 UTC
Labels: Component: Frontend, Difficulty: Easy, Priority: High, Status: Done, Type: Enhancement
