### ISSUE TITLE
Create setting to store user preference for task sort order

### ISSUE THREAD

**Issue by rtbk91** [hotosm/tasking-manager#5022] opened 2022-03-02 10:41 UTC
As a validator, I would like to be able to sort the tasks in all project the same way. I would like to be able to be able to store my preference in the settings.

Currently the default sort order is to sort by 'most recently updated' and for some users it would be useful to sort by other methods such as 'least recently updated'

**Comment by HelNershingThapa** [comment] 2022-05-10 05:24
Duplicate of #4847

**Closed by HelNershingThapa** 2022-05-10 05:24 UTC
