### ISSUE TITLE
Token not found, maybe you disabled cookie

### ISSUE THREAD

**Issue by mitchellspryn** [hotosm/tasking-manager#1391] opened 2019-03-16 22:37 UTC
When running the server locally, I get the following error when attempting to log in. I've already set up the TM_x environment variables (e.g. TM_DB, TM_CONSUMER_KEY, TM_CONSUMER_SECRET, TM_SECRET, etc) as specified in the instructions. This happens both in a standalone install and in the docker file:

```
[2019-03-16 15:32:55,552] ERROR in app: Exception on /api/v1/auth/oauth-callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mitchell/TaskingManager/tasking-manager/server/api/users/authentication_apis.py", line 65, in get
    osm_resp = osm.authorized_response()
  File "/usr/local/lib/python3.6/dist-packages/flask_oauthlib/client.py", line 683, in authorized_response
    data = self.handle_oauth1_response()
  File "/usr/local/lib/python3.6/dist-packages/flask_oauthlib/client.py", line 609, in handle_oauth1_response
    type='token_not_found'
flask_oauthlib.client.OAuthException: Token not found, maybe you disabled cookie
```

**Comment by uwaiszaki** [comment] 2019-03-17 05:25
I had the same error while trying to log in.

**Comment by xamanu** [comment] 2019-03-19 12:25
Hey, thanks for reporting this error. May I ask you to test the following:

* Install a recent version of [Docker](https://docs.docker.com/get-started/) and [Docker Compose](https://docs.docker.com/compose/).
* Check out the code: `git clone https://github.com/hotosm/tasking-manager.git && cd tasking-manager`
* Copy the configuration file `cp env-example .env`
* Add the consumer key and secret in the `.env` file.
* Run the system: `docker-compose up`
* Test whether logging in works under http://127.0.0.1:5000

**Comment by xamanu** [comment] 2019-03-19 12:31
This issue here seems to be a duplicate of #1388

**Comment by uwaiszaki** [comment] 2019-03-21 19:32
@xamanu I am unable to find the .env file. Can u please tell me where to find it?

**Comment by uwaiszaki** [comment] 2019-03-23 22:11
is this because of the port exposed?

**Comment by uwaiszaki** [comment] 2019-03-23 22:18
@xamanu It solved the issue.

**Comment by xamanu** [comment] 2019-03-26 11:56
I just tried an installation, without Docker Compose and got the same error. This makes the PR #1394 more urgent.

**Closed** 2019-03-27 13:23 UTC
Labels: Type: Question
