### ISSUE TITLE
Fix deprecated nodejs packages

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1472] opened 2019-04-10 07:35 UTC
We use a lot of deprecated nodejs packages. Let's update the nodejs packages to the latest version.

cc/ @hotosm/tech

**Comment by xamanu** [comment] 2019-04-10 17:07
Just as a side note: This is a follow up to #1448.

**Comment by xamanu** [comment] 2019-04-10 17:59
This is a duplicate of #901

**Closed by xamanu** 2019-04-10 17:59 UTC
Labels: Difficulty: Easy, Priority: Low, Type: Enhancement
